services:
  nuxt-container:
    build: .
    expose:
      - '3000' # 仅暴露给其他容器使用，不映射到宿主机
    networks:
      - app-network

  nginx-container:
    image: nginx:latest
    container_name: nuxt-nginx
    ports:
      - '80:80' # 监听 HTTP 的默认端口
      - '443:443' # 监听 HTTPS 的默认端口
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificate.pem:/etc/nginx/ssl/certificate.pem
      - ./private.key:/etc/nginx/ssl/private.key
    depends_on:
      - nuxt-container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
